<Project>
    <PropertyGroup>
        <BaseOutputPath>out</BaseOutputPath>
        <OutputPath>out</OutputPath>
        <Configuration></Configuration>
        <Platform></Platform>
        <appname>pa</appname>
        <builtdir>out</builtdir>
        <OutDir>out</OutDir>
        <builtdir>out</builtdir>
    </PropertyGroup>
</Project>