<Project>
    <PropertyGroup>
        <BaseOutputPath></BaseOutputPath>
        <OutputPath></OutputPath>
        <Configuration></Configuration>
        <Platform></Platform>
        <appname>pa</appname>
        <builtdir>out</builtdir>
        <OutDir></OutDir>
        <builtdir>out</builtdir>
    </PropertyGroup>
</Project>