<Project>
    <PropertyGroup></PropertyGroup>
    <Target Name="Clean">
    <Message Text="Cleaning"></Message>
    <RemoveDir Directories="$(builtdir)"/>
  </Target>
  <Target Name="Build">
    <Message Text="Build"></Message>
    <MakeDir Directories= "$(builtdir)" Condition ="!Exists('$(builtdir)')"/>
    <Csc Sources= "@(Compile)" OutputAssembly="$(BuiltDir\$(appname).exe">
    <Output TaskParameter="OutputAssembly" ItemName = "EXEFile"/>
    </Csc>
    </Target>
</Project>