<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="Algorithm.cs"/>
    <Compile Include="Input.cs"/>
    <Compile Include="ArrayList.cs"/>
    <Compile Include="PAElement.cs"/>
    <Compile Include="PAStatus.cs"/>
    <Compile Include="PAData.cs"/>
    <Compile Include="ArrayListPosition.cs"/>
  </ItemGroup>
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <TargetFrameworks>net20</TargetFrameworks>
    <!--<TargetFrameworkIdentifier>.NETFramework</TargetFrameworkIdentifier>-->
    <!---<TargetFrameworkVersion>v4.0</TargetFrameworkVersion>-->
    <Configuration>Debug</Configuration>
    <Platform>AnyCPU</Platform>
    <BaseOutputPath></BaseOutputPath>
    <OutputPath></OutputPath>
    <builtdir>dll</builtdir>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace>PA_Library</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!--<PackageReference Include="System.Collections.Immutable" Version="9.0.2" />-->
  </ItemGroup>

  <Target Name="Clean">
    <Message Text="Cleaning"></Message>
    <RemoveDir Directories="$(builtdir)"/>
  </Target>
  <Target Name="Build">
    <Message Text="Build"></Message>
    <MakeDir Directories= "$(builtdir)" Condition ="!Exists('$(builtdir)')"/>
    <Csc Sources= "@(Compile)" OutputAssembly="$(BuiltDir\$(appname).exe">
      <Output TaskParameter="OutputAssembly" ItemName = "EXEFile"/>
    </Csc>
  </Target>



</Project>
