<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="Algorithm.cs"/>
    <Compile Include="Input.cs"/>
    <Compile Include="ArrayList.cs"/>
    <Compile Include="PAElement.cs"/>
    <Compile Include="PAStatus.cs"/>
    <Compile Include="PAData.cs"/>
    <Compile Include="ArrayListPosition.cs"/>
    <Compile Include="PAResource.cs"/>
    <Compile Include="PAList.cs"/>
    <Compile Include="PASeries.cs"/>
    <Compile Include="PACount.cs"/>
    <Compile Include="Output.cs"/>
    <Compile Include="BFSRecord.cs"/>
    <Compile Include="PANumber.cs"/>
  </ItemGroup>
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <TargetFrameworks>net20</TargetFrameworks>
    <!--<TargetFrameworkIdentifier>.NETFramework</TargetFrameworkIdentifier>-->
    <!---<TargetFrameworkVersion>v4.0</TargetFrameworkVersion>-->
    <Configuration>Debug</Configuration>
    <Platform>AnyCPU</Platform>
    <BaseOutputPath></BaseOutputPath>
    <OutputPath></OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace>PA_Library</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!--<PackageReference Include="System.Collections.Immutable" Version="9.0.2" />-->
  </ItemGroup>
</Project>
