<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>PA_Library</RootNamespace>
  </PropertyGroup>
    <!--<PackageReference Include="System.Collections.Immutable" Version="9.0.2" />-->
  <ItemGroup>
    <Reference Include="Microsoft.CSharp">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Core">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Runtime.InteropServices">
      <RequiredTargetFramework>netstandard2.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Xml.Linq">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
  </ItemGroup>
</Project>
