<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <PropertyGroup>
  <Configuration>Debug</Configuration>
  <Platform>AnyCPU</Platform>
  <TargetFramework>.NETFramework</TargetFramework>
  <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
    <!--<RootNamespace>PA_Library</RootNamespace>-->
  </PropertyGroup>

  <ItemGroup>
    <!-- <PackageReference Include="System.Collections.Immutable" Version="9.0.2" /> -->
  </ItemGroup>

</Project>
